# docker compose -p macos_project up --build -- Run from scratch
# docker compose -p macos_project up -- Run previously created
# docker compose -p macos_project build --no-cache proxy -- Recreate proxy
# docker system prune -- Remove everything

# Steps:
# clean vds, ubuntu 24.04
# install xcfe4, vnc setup
# docker install
# clone repo, create .env from .env.example
# run "docker compose -p macos_project up --build"

version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./wireguard:/config
      - ./custom-cont-init.d:/etc/cont-init.d
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "wg", "show"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  checkip:
    image: curlimages/curl:latest
    container_name: checkip
    network_mode: service:wireguard
    depends_on:
      wireguard:
        condition: service_healthy
    entrypoint: >
      sh -c "
      curl -s http://ifconfig.me && echo"

  vnc-test:
    image: consol/rocky-xfce-vnc
    container_name: vnc-test
    network_mode: service:wireguard
    environment:
      - VNC_PASSWORD=testpassword  # Set a VNC password
    restart: unless-stopped

  vnc-proxy:
    image: alpine/socat
    container_name: vnc-proxy
    command: tcp-listen:5902,fork,reuseaddr tcp-connect:host.docker.internal:5901
    networks:
      - bypass_wireguard
    ports:
      - "5902:5902"
    depends_on:
      - vnc-test
    restart: unless-stopped

networks:
  bypass_wireguard:
    driver: bridge

  # dnsleaktest:
  #   image: python:alpine
  #   container_name: dnsleaktest
  #   network_mode: container:wireguard
  #   depends_on:
  #     wireguard:
  #       condition: service_healthy
  #   entrypoint: >
  #     sh -c "
  #     wget -q -O- https://raw.githubusercontent.com/macvk/dnsleaktest/master/dnsleaktest.py | python"

  # macos:
  #   image: sickcodes/docker-osx:latest
  #   container_name: macos-13
  #   privileged: true
  #   network_mode: container:wireguard
  #   devices:
  #     - "/dev/kvm:/dev/kvm"
  #   depends_on:
  #     wireguard:
  #       condition: service_healthy
  #   environment:
  #     - RAM=16
  #     - GENERATE_UNIQUE=true
  #     - DEVICE_MODEL=${DEVICE_MODEL}
  #     - MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
  #     - SHORTNAME=ventura
  #     - EXTRA=-display none -vnc 0.0.0.0:99
    # volumes:
    #   - "${PWD}/output.env:/env"