# docker compose -p macos_project up --build
# docker compose -p macos_project up

version: "3.8"

services:
  proxy:
    build: ./proxy
    container_name: proxy
    privileged: true
    ports:
      - "50922:10022"
      - "5999:5999"
    environment:
      PROXY_IP: ${PROXY_IP}
      PROXY_PORT: ${PROXY_PORT}
      PROXY_USER: ${PROXY_USER}
      PROXY_PASS: ${PROXY_PASS}
    healthcheck:
      test: ["CMD", "cat", "/tmp/redsocks_ready"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s

  macos:
    image: sickcodes/docker-osx:latest
    container_name: macos-13
    depends_on:
      proxy:
        condition: service_healthy
    network_mode: container:proxy
    devices:
      - "/dev/kvm:/dev/kvm"
    environment:
      - GENERATE_UNIQUE=true
      - DEVICE_MODEL=MacBookPro16,1
      - MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
      - SHORTNAME=ventura
      - EXTRA=-display none -vnc 0.0.0.0:99