# docker compose -p macos_project up --build -- Run from scratch
# docker compose -p macos_project up -- Run previously created
# docker compose -p macos_project build --no-cache proxy -- Recreate proxy
# docker system prune -- Remove everything

# Steps:
# clean vds, ubuntu 24.04
# install xcfe4, vnc setup
# docker install
# clone repo, create .env from .env.example
# run "docker compose -p macos_project up --build"

version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom  # Use 'custom' for manual WireGuard configuration
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=gFu2QeeoHLfAb5JI0QCwVTJWdeCDD+4sk9J0XvHNKFs=
      - WIREGUARD_ADDRESSES=10.66.66.2/32
      - WIREGUARD_ENDPOINT_IP=217.30.10.70
      - WIREGUARD_ENDPOINT_PORT=51249
      - WIREGUARD_PUBLIC_KEY=Nl00anlFpc371uLu9FBVEnB8iQp/rgACkf6nu+M4Ryo=
      - WIREGUARD_PRESHARED_KEY=3CnHMTrIxRVr7eQh5U6316Yf4/YdoXYoLgE4opUT/zY=
      - FIREWALL_INPUT_PORTS=80  # Allow VNC port
    ports:
      - "8080:80/tcp"
    restart: unless-stopped

  checkip:
    image: curlimages/curl:latest
    container_name: checkip
    network_mode: service:gluetun
    entrypoint: >
      sh -c "
      curl -s http://ifconfig.me && echo"

  nginx-test:
    image: nginx:alpine
    container_name: nginx-test
    network_mode: "service:gluetun"  # Shares Gluetun's network stack
    restart: unless-stopped

  # dnsleaktest:
  #   image: python:alpine
  #   container_name: dnsleaktest
  #   network_mode: container:wireguard
  #   depends_on:
  #     wireguard:
  #       condition: service_healthy
  #   entrypoint: >
  #     sh -c "
  #     wget -q -O- https://raw.githubusercontent.com/macvk/dnsleaktest/master/dnsleaktest.py | python"

  # macos:
  #   image: sickcodes/docker-osx:latest
  #   container_name: macos-13
  #   privileged: true
  #   network_mode: container:wireguard
  #   devices:
  #     - "/dev/kvm:/dev/kvm"
  #   depends_on:
  #     wireguard:
  #       condition: service_healthy
  #   environment:
  #     - RAM=16
  #     - GENERATE_UNIQUE=true
  #     - DEVICE_MODEL=${DEVICE_MODEL}
  #     - MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
  #     - SHORTNAME=ventura
  #     - EXTRA=-display none -vnc 0.0.0.0:99
    # volumes:
    #   - "${PWD}/output.env:/env"