# docker compose -p macos_project up --build -- Run from scratch
# docker compose -p macos_project up -- Run previously created
# docker compose -p macos_project build --no-cache proxy -- Recreate proxy
# docker system prune -- Remove everything

# Steps:
# clean vds, ubuntu 24.04
# install xcfe4, vnc setup
# docker install
# clone repo, create .env from .env.example
# run "docker compose -p macos_project up --build"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom  # Use 'custom' for manual WireGuard configuration
      - VPN_TYPE=wireguard
      - FIREWALL_INPUT_PORTS=5999  # Allow VNC port
    volumes:
      - "${PWD}/wg0.conf:/gluetun/wireguard/wg0.conf"
    ports:
      - "5999:5999/tcp"  # Expose VNC port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ipinfo.io"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  macos:
    image: sickcodes/docker-osx:latest
    container_name: macos-13
    privileged: true
    network_mode: service:gluetun  # Use the gluetun network stack
    depends_on:
      gluetun:
        condition: service_healthy
    devices:
      - /dev/kvm
    environment:
      - RAM=16
      - GENERATE_UNIQUE=true
      - DEVICE_MODEL=${DEVICE_MODEL}
      - MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
      - SHORTNAME=ventura
      - EXTRA=-vnc 0.0.0.0:99
      - DISPLAY=${DISPLAY:-:0.0}
    volumes:
      - "tmp/.X11-unix:/tmp/.X11-unix"
    #   - "${PWD}/output.env:/env"