# PROXY_MODE=container:proxy docker compose -p macos_project up --build
# PROXY_MODE=bridge docker compose -p macos_project up --build

# PROXY_MODE=container:proxy docker compose -p macos_project up
# PROXY_MODE=bridge docker compose -p macos_project up

version: "3.8"

services:
  proxy:
    build: ./proxy
    container_name: proxy
    privileged: true
    ports:
      - "50922:10022"
      - "5999:5999"
    environment:
      PROXY_IP: "142.252.4.175"
      PROXY_PORT: "62769"
      PROXY_USER: "FW1afJLA"
      PROXY_PASS: "3HXPrZEc"
    healthcheck:
      test: ["CMD", "cat", "/tmp/redsocks_ready"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s

  macos:
    image: sickcodes/docker-osx:latest
    container_name: macos-13
    depends_on:
      proxy:
        condition: service_healthy
    network_mode: ${PROXY_MODE:-bridge}
    devices:
      - "/dev/kvm:/dev/kvm"
    ports:
      - "50923:10022"
      - "6000:5999"
    environment:
      - GENERATE_UNIQUE=true 
      - DEVICE_MODEL=MacBookPro16,1
      - MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
      - SHORTNAME=ventura
      - EXTRA=-display none -vnc 0.0.0.0:99,password=on -monitor stdio
      - VNC_PASSWORD=qwerty