services:
  macos:
    image: sickcodes/docker-osx:latest
    container_name: macos-13
    privileged: true
    devices:
      - /dev/kvm
    ports:
      - "5999:5999/tcp"  # Expose VNC port
    environment:
      - RAM=16
      - GENERATE_UNIQUE=true
      - DEVICE_MODEL=${DEVICE_MODEL}
      - MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
      - SHORTNAME=ventura
      - EXTRA=-display none -vnc 0.0.0.0:99
      - WIDTH=1280
      - HEIGHT=720