services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - /lib/modules:/lib/modules:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom  # Use 'custom' for manual WireGuard configuration
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - FIREWALL_INPUT_PORTS=5999
    ports:
      - "5999:5999/tcp"  # Expose VNC port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ipinfo.io"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s