services:
  macos:
    image: dockurr/macos
    container_name: macos
    privileged: true
    ports:
      - "8006:8006"
    devices:
      - /dev/kvm
      - /dev/net/tun
    volumes:
      - ./data:/storage
    environment:
      - VERSION=14
      - MODEL=${DEVICE_MODEL}
      - RAM_SIZE=16G
      - CPU_CORES=6
    stop_grace_period: 2m